#!/usr/bin/env bun
/**
 * Build (or stage) the matching omp-tui Go frontend and embed it for bun --compile,
 * or stage every supported target for the npm source package.
 *
 * --generate (default when not --reset / --reset-packaged / --all-targets):
 *   1. Resolve RATATUI_GO_ROOT (default sibling checkout)
 *   2. Cross-compile ./cmd/omp-tui for TARGET_PLATFORM/TARGET_ARCH (or host)
 *   3. Copy binary next to embedded-omp-tui.ts and rewrite that module with
 *      `with { type: "file" }` + size + sha256 metadata
 *
 * --all-targets:
 *   Cross-compile every OMP_TUI_GO_TARGETS entry into
 *   src/modes/go-tui/binaries/omp-tui.<platform>-<arch>[.exe] for npm pack.
 *   Does not rewrite the embed placeholder. Bounded parallel go build.
 *
 * --dry-run (with --all-targets or alone for single-target plan):
 *   Print the go build plans (GOOS/GOARCH/command argv) without executing.
 *
 * --reset:
 *   Restore the checked-in null placeholder and delete known generated artifacts.
 *
 * --reset-packaged:
 *   Delete only known staged multi-target binaries (postpack / prepack failure).
 *   Does not touch the embed placeholder.
 *
 * Build fails hard if the Go artifact cannot be produced or is missing —
 * never silently ship a TS-only interactive frontend in release binaries.
 *
 * Does not copy Go source into OMP. Never network-fetches a binary.
 * Concurrent pack/build safety: task-unique temp outputs + atomic rename;
 * cleanup only deletes known final names.
 */
import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import {
	OMP_TUI_PACKAGE,
	RATATUI_GO_MODULE,
	RATATUI_GO_REVISION_ENV,
	RATATUI_GO_ROOT_ENV,
} from "../src/modes/go-tui/constants";
import {
	defaultRatatuiGoRoot,
	OMP_TUI_GO_TARGETS,
	type OmpTuiGoTarget,
	ompTuiBinaryName,
	ompTuiPlatformTag,
	ompTuiStagedBinaryName,
	ompTuiStagedBinaryNames,
} from "../src/modes/go-tui/resolve-binary";

const packageDir = path.join(import.meta.dir, "..");
const goTuiDir = path.join(packageDir, "src", "modes", "go-tui");
const binariesDir = path.join(goTuiDir, "binaries");
const helperPath = path.join(goTuiDir, "embedded-omp-tui.ts");
const packageJsonPath = path.join(packageDir, "package.json");

const reset = process.argv.includes("--reset");
const resetPackaged = process.argv.includes("--reset-packaged");
const stageOnly = process.argv.includes("--stage-only");
const skipBuild = process.argv.includes("--skip-build");
const allTargets = process.argv.includes("--all-targets");
const dryRun = process.argv.includes("--dry-run");

/** Max concurrent `go build` processes for --all-targets. */
const ALL_TARGETS_PARALLELISM = Math.max(1, Math.min(4, os.cpus().length || 2));

const KNOWN_EMBED_COPY_NAMES = ["omp-tui.embedded", "omp-tui.embedded.exe"] as const;
const LEGACY_BARE_NAMES = ["omp-tui", "omp-tui.exe"] as const;

const interfaceBlock = `export interface EmbeddedOmpTui {
	/** Host platform tag, e.g. "darwin-arm64". */
	platformTag: string;
	/** OMP package version used as the extract cache key. */
	version: string;
	/** On-disk basename including .exe on Windows. */
	filename: string;
	/** Byte length of the embedded binary (checksum/size gate). */
	size: number;
	/** Lowercase hex SHA-256 of the embedded bytes. */
	sha256: string;
	/**
	 * Absolute path into bunfs (or a real path during the generate step) for the
	 * embedded binary bytes. Present only when generated.
	 */
	filePath?: string;
}`;

const placeholder = `// AUTOGENERATED -- managed by scripts/embed-omp-tui.ts. Do not edit by hand.
//
// Compiled single-file binaries embed the matching omp-tui frontend via
// \`with { type: "file" }\`. Source checkouts, bun test, and the npm dist/cli.js
// bundle keep this placeholder (null) and resolve a staged/dev binary instead.
// The binary build regenerates this module and resets it afterward.
// npm pack stages platform binaries under ./binaries/ via --all-targets.

${interfaceBlock}

/** Placeholder: no frontend embedded outside the binary build. */
export const embeddedOmpTui: EmbeddedOmpTui | null = null;
`;

/** One cross-compile plan — argv array, never a shell string. */
export interface OmpTuiGoBuildPlan {
	target: OmpTuiGoTarget;
	/** Final staged path under binaries/. */
	outputPath: string;
	/** Task-unique temp path; go build writes here, then atomic rename. */
	tempPath: string;
	cwd: string;
	command: string[];
	env: {
		CGO_ENABLED: "0";
		GOOS: string;
		GOARCH: string;
	};
}

export type OmpTuiGoBuildRunner = (plan: OmpTuiGoBuildPlan) => Promise<void>;

function resolveTarget(): OmpTuiGoTarget {
	const platform = (Bun.env.TARGET_PLATFORM || process.platform) as OmpTuiGoTarget["platform"];
	const arch = (Bun.env.TARGET_ARCH || process.arch) as OmpTuiGoTarget["arch"];
	const id = `${platform}-${arch}`;
	const found = OMP_TUI_GO_TARGETS.find(t => t.id === id);
	if (!found) {
		throw new Error(
			`Unsupported omp-tui embed target ${id}. Supported: ${OMP_TUI_GO_TARGETS.map(t => t.id).join(", ")}`,
		);
	}
	return found;
}

function ratatuiGoRoot(): string {
	const fromEnv = Bun.env[RATATUI_GO_ROOT_ENV]?.trim();
	if (fromEnv) return path.resolve(fromEnv);
	return defaultRatatuiGoRoot();
}

function uniqueTempName(target: OmpTuiGoTarget): string {
	const exe = target.platform === "win32" ? ".exe" : "";
	const rand = Math.random().toString(16).slice(2);
	return `.omp-tui.${target.id}.${process.pid}.${Date.now()}.${rand}.tmp${exe}`;
}

/** Build the argv/env plan for one target. Pure — no I/O. */
export function planGoBuild(
	target: OmpTuiGoTarget,
	options?: {
		root?: string;
		binariesDir?: string;
		outputPath?: string;
	},
): OmpTuiGoBuildPlan {
	const root = options?.root ?? ratatuiGoRoot();
	const outDir = options?.binariesDir ?? binariesDir;
	const outputPath = options?.outputPath ?? path.join(outDir, ompTuiStagedBinaryName(target));
	const tempPath = path.join(path.dirname(outputPath), uniqueTempName(target));
	return {
		target,
		outputPath,
		tempPath,
		cwd: root,
		command: ["go", "build", "-trimpath", "-ldflags=-s -w", "-o", tempPath, OMP_TUI_PACKAGE],
		env: {
			CGO_ENABLED: "0",
			GOOS: target.goos,
			GOARCH: target.goarch,
		},
	};
}

/** Plans for every supported target (deterministic order = OMP_TUI_GO_TARGETS). */
export function planAllTargetBuilds(options?: { root?: string; binariesDir?: string }): OmpTuiGoBuildPlan[] {
	const root = options?.root ?? ratatuiGoRoot();
	const outDir = options?.binariesDir ?? binariesDir;
	return OMP_TUI_GO_TARGETS.map(target => planGoBuild(target, { root, binariesDir: outDir }));
}

async function runCommand(command: string[], cwd: string, env: NodeJS.ProcessEnv = Bun.env): Promise<void> {
	const proc = Bun.spawn(command, {
		cwd,
		env,
		stdout: "inherit",
		stderr: "inherit",
	});
	const code = await proc.exited;
	if (code !== 0) {
		throw new Error(`Command failed (${code}): ${command.join(" ")}`);
	}
}

async function readGitHeadRevision(root: string): Promise<string> {
	const proc = Bun.spawn(["git", "rev-parse", "HEAD"], {
		cwd: root,
		stdout: "pipe",
		stderr: "pipe",
	});
	const [stdout, stderr, code] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	]);
	if (code !== 0) {
		throw new Error(`Unable to resolve ratatui-go revision at ${root}: ${stderr.trim() || `git exited ${code}`}`);
	}
	return stdout.trim();
}

async function pathExists(p: string): Promise<boolean> {
	try {
		await fs.access(p);
		return true;
	} catch {
		return false;
	}
}

async function unlinkIfExists(p: string): Promise<void> {
	try {
		await fs.unlink(p);
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
}
/** Delete only known staged multi-target final names under binaries/. */
async function cleanPackagedBinaries(): Promise<void> {
	// Never wipe arbitrary directory contents or another task's temp —
	// only the deterministic final basenames from OMP_TUI_GO_TARGETS.
	await Promise.all(ompTuiStagedBinaryNames().map(name => unlinkIfExists(path.join(binariesDir, name))));
}

async function resetPackagedArtifacts(): Promise<void> {
	await cleanPackagedBinaries();
	console.log("Reset packaged omp-tui staged binaries");
}

async function resetEmbed(): Promise<void> {
	await Bun.write(helperPath, placeholder);
	// Only known final names — never wipe another pack/build task's temp outputs.
	await cleanPackagedBinaries();
	for (const name of [...KNOWN_EMBED_COPY_NAMES, ...LEGACY_BARE_NAMES]) {
		await unlinkIfExists(path.join(goTuiDir, name));
	}
	console.log("Reset embedded-omp-tui.ts placeholder");
}

async function assertRatatuiGoReady(root: string): Promise<void> {
	const modPath = path.join(root, "go.mod");
	if (!(await pathExists(modPath))) {
		throw new Error(
			`RATATUI_GO_ROOT=${root} has no go.mod. ` +
				`Set ${RATATUI_GO_ROOT_ENV} to the ratatui-go checkout (default: sibling of oh-my-pi). ` +
				`Refusing to ship a TS-only binary.`,
		);
	}
	const moduleLine = (await fs.readFile(modPath, "utf8")).split(/\r?\n/, 1)[0]?.trim();
	if (moduleLine !== `module ${RATATUI_GO_MODULE}`) {
		throw new Error(
			`RATATUI_GO_ROOT=${root} declares ${moduleLine || "no module"}; expected module ${RATATUI_GO_MODULE}.`,
		);
	}
	const mainFile = path.join(root, "cmd", "omp-tui", "main.go");
	// Empty dir is not enough — FrontendAppPort may mkdir before landing sources.
	if (!(await pathExists(mainFile))) {
		throw new Error(
			`omp-tui main package not found at ${mainFile}. ` +
				`FrontendAppPort must land cmd/omp-tui before release embed. ` +
				`Refusing to ship a TS-only binary.`,
		);
	}
	const expectedRevision = Bun.env[RATATUI_GO_REVISION_ENV]?.trim();
	if (expectedRevision) {
		if (!/^[0-9a-f]{40}$/.test(expectedRevision)) {
			throw new Error(`${RATATUI_GO_REVISION_ENV} must be a full lowercase 40-character Git SHA.`);
		}
		const actualRevision = await readGitHeadRevision(root);
		if (actualRevision !== expectedRevision) {
			throw new Error(
				`RATATUI_GO_ROOT=${root} is at ${actualRevision}; expected pinned revision ${expectedRevision}.`,
			);
		}
	}
}

function defaultBuildRunner(): OmpTuiGoBuildRunner {
	return async plan => {
		const buildEnv = {
			...Bun.env,
			CGO_ENABLED: plan.env.CGO_ENABLED,
			GOOS: plan.env.GOOS,
			GOARCH: plan.env.GOARCH,
		};
		console.log(
			`Building omp-tui (${plan.target.id}) GOOS=${plan.env.GOOS} GOARCH=${plan.env.GOARCH} → ${plan.outputPath}`,
		);
		try {
			await runCommand(plan.command, plan.cwd, buildEnv);
			if (!(await pathExists(plan.tempPath))) {
				throw new Error(`go build reported success but ${plan.tempPath} is missing`);
			}
			await fs.chmod(plan.tempPath, 0o755).catch(() => {});
			// Atomic replace of the final staged name.
			await fs.rename(plan.tempPath, plan.outputPath);
			await fs.chmod(plan.outputPath, 0o755).catch(() => {});
		} catch (err) {
			await unlinkIfExists(plan.tempPath);
			throw err;
		}
	};
}

/** Run async work over items with a fixed concurrency cap. */
async function mapPool<T>(items: readonly T[], concurrency: number, fn: (item: T) => Promise<void>): Promise<void> {
	if (items.length === 0) return;
	const limit = Math.max(1, Math.min(concurrency, items.length));
	let next = 0;
	const workers = Array.from({ length: limit }, async () => {
		while (true) {
			const i = next++;
			if (i >= items.length) return;
			await fn(items[i]!);
		}
	});
	await Promise.all(workers);
}

function printPlan(plan: OmpTuiGoBuildPlan): void {
	const envStr = `CGO_ENABLED=${plan.env.CGO_ENABLED} GOOS=${plan.env.GOOS} GOARCH=${plan.env.GOARCH}`;
	console.log(`[dry-run] ${plan.target.id}: ${envStr} ${plan.command.join(" ")} (cwd=${plan.cwd})`);
}

async function stageAllTargets(runner: OmpTuiGoBuildRunner = defaultBuildRunner()): Promise<void> {
	const root = ratatuiGoRoot();
	const plans = planAllTargetBuilds({ root, binariesDir });

	if (dryRun) {
		for (const plan of plans) printPlan(plan);
		console.log(`[dry-run] ${plans.length} omp-tui targets (parallelism=${ALL_TARGETS_PARALLELISM})`);
		return;
	}

	await assertRatatuiGoReady(root);
	await fs.mkdir(binariesDir, { recursive: true });

	// Do not wipe other known targets before the full matrix finishes — write
	// each via temp+rename so a failed target leaves prior good artifacts alone
	// until the whole run succeeds. On failure, prepack cleanup removes known names.
	await mapPool(plans, ALL_TARGETS_PARALLELISM, async plan => {
		await runner(plan);
		if (!(await pathExists(plan.outputPath))) {
			throw new Error(`staged omp-tui missing after build: ${plan.outputPath}`);
		}
	});

	for (const plan of plans) {
		if (!(await pathExists(plan.outputPath))) {
			throw new Error(`omp-tui target ${plan.target.id} missing at ${plan.outputPath}`);
		}
	}
	console.log(`Staged ${plans.length} omp-tui targets under ${path.relative(packageDir, binariesDir)}`);
}

async function ensureGoBinary(target: OmpTuiGoTarget): Promise<string> {
	await fs.mkdir(binariesDir, { recursive: true });
	const stagedName = ompTuiStagedBinaryName(target);
	const stagedPath = path.join(binariesDir, stagedName);

	const inputFlag = process.argv.find(a => a.startsWith("--input="));
	const inputPath = inputFlag ? inputFlag.slice("--input=".length) : undefined;
	if (inputPath) {
		const abs = path.resolve(inputPath);
		if (!(await pathExists(abs))) {
			throw new Error(`--input ${abs} does not exist`);
		}
		const tempPath = path.join(binariesDir, uniqueTempName(target));
		try {
			await fs.copyFile(abs, tempPath);
			await fs.chmod(tempPath, 0o755).catch(() => {});
			await fs.rename(tempPath, stagedPath);
		} catch (err) {
			await unlinkIfExists(tempPath);
			throw err;
		}
		await fs.chmod(stagedPath, 0o755).catch(() => {});
		return stagedPath;
	}

	if (skipBuild) {
		if (!(await pathExists(stagedPath))) {
			throw new Error(`--skip-build set but ${stagedPath} is missing. Build omp-tui first or pass --input=`);
		}
		return stagedPath;
	}

	const root = ratatuiGoRoot();
	await assertRatatuiGoReady(root);
	const plan = planGoBuild(target, { root, binariesDir, outputPath: stagedPath });
	if (dryRun) {
		printPlan(plan);
		return stagedPath;
	}
	await defaultBuildRunner()(plan);
	return stagedPath;
}

async function generateEmbed(): Promise<void> {
	const target = resolveTarget();
	const packageJson = (await Bun.file(packageJsonPath).json()) as { version: string };
	const version = packageJson.version;

	if (dryRun && !skipBuild && !process.argv.some(a => a.startsWith("--input="))) {
		const plan = planGoBuild(target);
		printPlan(plan);
		return;
	}

	const binaryPath = await ensureGoBinary(target);
	const bytes = await fs.readFile(binaryPath);
	const size = bytes.byteLength;
	const sha256 = createHash("sha256").update(bytes).digest("hex");
	const platformTag = ompTuiPlatformTag(target.platform as NodeJS.Platform, target.arch);
	const filename = ompTuiBinaryName(target.platform as NodeJS.Platform);

	const embedCopyName = target.platform === "win32" ? "omp-tui.embedded.exe" : "omp-tui.embedded";
	const embedCopyPath = path.join(goTuiDir, embedCopyName);
	// Atomic write for the embed copy too.
	const embedTemp = path.join(
		goTuiDir,
		`.${embedCopyName}.${process.pid}.${Date.now()}.${Math.random().toString(16).slice(2)}.tmp`,
	);
	try {
		await Bun.write(embedTemp, bytes);
		await fs.chmod(embedTemp, 0o755).catch(() => {});
		await fs.rename(embedTemp, embedCopyPath);
		await fs.chmod(embedCopyPath, 0o755).catch(() => {});
	} catch (err) {
		await unlinkIfExists(embedTemp);
		throw err;
	}

	if (stageOnly) {
		console.log(`Staged omp-tui at ${binaryPath} (${size} bytes, sha256=${sha256}) --stage-only, skip rewrite`);
		return;
	}

	const generated = `// AUTOGENERATED -- managed by scripts/embed-omp-tui.ts. Do not edit or commit.
import filePath from ${JSON.stringify(`./${embedCopyName}`)} with { type: "file" };

${interfaceBlock}

export const embeddedOmpTui: EmbeddedOmpTui = {
	platformTag: ${JSON.stringify(platformTag)},
	version: ${JSON.stringify(version)},
	filename: ${JSON.stringify(filename)},
	size: ${size},
	sha256: ${JSON.stringify(sha256)},
	filePath,
};
`;

	await Bun.write(helperPath, generated);
	console.log(
		`Embedded omp-tui ${platformTag} v${version} (${size} bytes, sha256=${sha256.slice(0, 12)}…) → ${path.relative(packageDir, helperPath)}`,
	);
}

async function main(): Promise<void> {
	if (resetPackaged) {
		await resetPackagedArtifacts();
		return;
	}
	if (reset) {
		await resetEmbed();
		return;
	}
	if (allTargets) {
		await stageAllTargets();
		return;
	}
	await generateEmbed();
}

// Only run CLI when this file is the entrypoint — importing plan helpers must not build.
const isMain =
	typeof Bun !== "undefined" && Boolean(Bun.main) && path.resolve(Bun.main) === path.resolve(import.meta.path);

if (isMain) {
	await main();
}
