// AUTOGENERATED -- managed by scripts/embed-omp-tui.ts. Do not edit by hand.
//
// Compiled single-file binaries embed the matching omp-tui frontend via
// `with { type: "file" }`. Source checkouts, bun test, and the npm dist/cli.js
// bundle keep this placeholder (null) and resolve a staged/dev binary instead.
// The binary build regenerates this module and resets it afterward.
// npm pack stages platform binaries under ./binaries/ via --all-targets.

export interface EmbeddedOmpTui {
	/** Host platform tag, e.g. "darwin-arm64". */
	platformTag: string;
	/** OMP package version used as the extract cache key. */
	version: string;
	/** On-disk basename including .exe on Windows. */
	filename: string;
	/** Byte length of the embedded binary (checksum/size gate). */
	size: number;
	/** Lowercase hex SHA-256 of the embedded bytes. */
	sha256: string;
	/**
	 * Absolute path into bunfs (or a real path during the generate step) for the
	 * embedded binary bytes. Present only when generated.
	 */
	filePath?: string;
}

/** Placeholder: no frontend embedded outside the binary build. */
export const embeddedOmpTui: EmbeddedOmpTui | null = null;
